CREATE TABLE [ZZ].[Customer_History] (
    [HID]                            INT              IDENTITY (1, 1) NOT NULL,
    [Action]                         INT              NOT NULL,
    [ActionTime]                     DATETIME         NOT NULL,
    [ID]                             INT              NOT NULL,
    [GUID]                           UNIQUEIDENTIFIER NOT NULL,
    [ExternalSystemCode]             NVARCHAR (50)    NULL,
    [EmailInteractionValidationGUID] UNIQUEIDENTIFIER NULL,
    [Email]                          NVARCHAR (255)   NOT NULL,
    [Password]                       NVARCHAR (50)    NOT NULL,
    [FirstName]                      NVARCHAR (255)   NOT NULL,
    [LastName]                       NVARCHAR (255)   NOT NULL,
    [GenderID]                       INT              NOT NULL,
    [MaritalStatusID]                INT              NULL,
    [EducationLevelID]               INT              NULL,
    [JobID]                          INT              NULL,
    [Birthday]                       DATETIME         NULL,
    [CellPhone]                      VARCHAR (20)     NULL,
    [LoyaltyCardNumber]              NVARCHAR (50)    NULL,
    [RegistrationOrigin]             CHAR   NULL,
    [RegisterIpAddress]              NVARCHAR (100)   NULL,
    [IsActivatedByEmail]             BIT              CONSTRAINT [DF_Customer_History_IsActivatedByEmail] DEFAULT ((0)) NOT NULL,
    [IsTransferredToExternalSystem]  BIT              CONSTRAINT [DF_Customer_History_IsTransferredToExternalSystem] DEFAULT ((0)) NOT NULL,
    [ExternalSystemTransferTime]     DATETIME         NULL,
    [IsActive]                       BIT              NOT NULL,
    [CreateUserID]                   INT              NOT NULL,
    [CreateTime]                     DATETIME         CONSTRAINT [DF_Customer_History_CreateTime] DEFAULT (getutcdate()) NOT NULL,
    [UpdateUserID]                   INT              NOT NULL,
    [UpdateTime]                     DATETIME         CONSTRAINT [DF_Customer_History_UpdateTime] DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_Customer_History] PRIMARY KEY CLUSTERED ([HID] ASC)
);

