//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entegral.ECommerce.DataContext.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM;Integrated Security=True")]
        public string ECOMConnectionString {
            get {
                return ((string)(this["ECOMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_INTEGRATION;Integrated Security=True")]
        public string ECOM_INTEGRATIONConnectionString {
            get {
                return ((string)(this["ECOM_INTEGRATIONConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM;Integrated Security=True;Application Name=ECOM" +
            "")]
        public string ECOMConnectionString1 {
            get {
                return ((string)(this["ECOMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM;Integrated Security=True")]
        public string ECOMConnectionString2 {
            get {
                return ((string)(this["ECOMConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM;Integrated Security=True")]
        public string ECOMHistoryConnectionString {
            get {
                return ((string)(this["ECOMHistoryConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_INTEGRATION;Integrated Security=True;Applicati" +
            "on Name=ECOM_INTEGRATION")]
        public string ECOM_INTEGRATIONConnectionString1 {
            get {
                return ((string)(this["ECOM_INTEGRATIONConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_MONITOR;Integrated Security=True")]
        public string ECOM_MONITORConnectionString {
            get {
                return ((string)(this["ECOM_MONITORConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_INTEGRATION;Integrated Security=True")]
        public string EComIntegrationConnectionString {
            get {
                return ((string)(this["EComIntegrationConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_MONITOR;Integrated Security=True")]
        public string EComMonitorConnectionString {
            get {
                return ((string)(this["EComMonitorConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_NEWDESIGN;Integrated Security=True")]
        public string ECOM_NEWDESIGNConnectionString {
            get {
                return ((string)(this["ECOM_NEWDESIGNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_NEWDESIGN;Integrated Security=True;Enlist=Fals" +
            "e;Connect Timeout=60;Application Name=ECOM")]
        public string ECOM_NEWDESIGNConnectionString1 {
            get {
                return ((string)(this["ECOM_NEWDESIGNConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_NEWDESIGN;Integrated Security=True;Connect Tim" +
            "eout=60;Application Name=ECOM")]
        public string ECOM_NEWDESIGNConnectionString2 {
            get {
                return ((string)(this["ECOM_NEWDESIGNConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_PACKAGE;Integrated Security=True")]
        public string EComPackageConnectionString {
            get {
                return ((string)(this["EComPackageConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_PACKAGE;Integrated Security=True;Connect Timeo" +
            "ut=60;Application Name=ECOM")]
        public string ECOM_PACKAGEConnectionString {
            get {
                return ((string)(this["ECOM_PACKAGEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_TEST;Integrated Security=True;Connect Timeout=" +
            "60;Application Name=ECOM")]
        public string ECOM_TESTConnectionString {
            get {
                return ((string)(this["ECOM_TESTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:hq4t6thnfv.database.windows.net,1433;Initial Catalog=ECOM_PACKAGE" +
            ";Integrated Security=False;User ID=ngidbuser@hq4t6thnfv;Password=NGI?innovation;" +
            "MultipleActiveResultSets=True;Connect Timeout=30;Encrypt=True")]
        public string ECOM_PACKAGEConnectionString1 {
            get {
                return ((string)(this["ECOM_PACKAGEConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ECOM_MONITOR;Integrated Security=True;Connect Timeo" +
            "ut=60;Application Name=ECOM_INTEGRATION")]
        public string ECOM_MONITORConnectionString1 {
            get {
                return ((string)(this["ECOM_MONITORConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:wrqsh5npmo.database.windows.net,1433;Initial Catalog=PROD_ECOM_PA" +
            "CKAGE;Integrated Security=False;User ID=ngidbuser@wrqsh5npmo;Password=NGI?innova" +
            "tion;MultipleActiveResultSets=True;Connect Timeout=30;Encrypt=True")]
        public string PROD_ECOM_PACKAGEConnectionString {
            get {
                return ((string)(this["PROD_ECOM_PACKAGEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:lztkl0li24.database.windows.net,1433;Initial Catalog=PROD_ECOM;Pe" +
            "rsist Security Info=True;User ID=beymendbuser@lztkl0li24;Password=mJao4Cqy")]
        public string PROD_ECOMConnectionString {
            get {
                return ((string)(this["PROD_ECOMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:lztkl0li24.database.windows.net,1433;Initial Catalog=Copy_PROD_EC" +
            "OM;User ID=beymendbuser@lztkl0li24;Password=mJao4Cqy;Enlist=False;MultipleActive" +
            "ResultSets=True;Connect Timeout=300")]
        public string Copy_PROD_ECOMConnectionString {
            get {
                return ((string)(this["Copy_PROD_ECOMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:es8ehthe1f.database.windows.net,1433;Initial Catalog=PROD_ECOM;Us" +
            "er ID=ngidbuser@es8ehthe1f;Enlist=False;MultipleActiveResultSets=True;Connect Ti" +
            "meout=60")]
        public string PROD_ECOMConnectionString1 {
            get {
                return ((string)(this["PROD_ECOMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:es8ehthe1f.database.windows.net,1433;Initial Catalog=PROD_ECOM;Us" +
            "er ID=ngidbuser@es8ehthe1f;Password=NGI?innovation;Enlist=False;MultipleActiveRe" +
            "sultSets=True;Connect Timeout=60")]
        public string PROD_ECOMConnectionString2 {
            get {
                return ((string)(this["PROD_ECOMConnectionString2"]));
            }
        }
    }
}
